set={10,4,7,87,9,89,89,89,"hgchxd"}
print(set)
print(type(set))
print( 9 in set)
set.add("hhg")
print(set)
set.update([7,98,"dfsdf"])
print(set)
set.remove(7)
print(set)
set.pop()
print(set)
set.discard('hhg')
print(set)
set.clear()
print(set)


set1={7,8,2,3,5,6,0}
set2={7,5,6,7,9,34,5,5}
print(set1|set2)
print(set1&set2)
print(set1.union(set2))
print(set1.intersection(set2))
print(set1-set2)
print(set1.difference(set2))
print(set2-set1)
print(set2.difference(set1))
print(set1.symmetric_difference(set2))
print(set1.symmetric_difference(set2))
print(set1^set2)
print(set1.isdisjoint(set2))
print(set1.issubset(set2))
print(set1.issuperset(set2))

seq3=input()
print(seq3)
print(seq3.replace("T","U"))

print(id(int(87)))
print(id(float(9.90)))
